version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diamond-diaries-app
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3000/api}
      - NEXT_PUBLIC_API_VERSION=${NEXT_PUBLIC_API_VERSION:-v1}
      - NEXT_IMAGE_DOMAINS=lh3.googleusercontent.com
    networks:
      - diamond-diaries-network
    # Add healthcheck to ensure container is running properly
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # Additional services can be added here
  # For example, if you add a database service in the future:
  # db:
  #   image: postgres:latest
  #   container_name: diamond-diaries-db
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_PASSWORD=your_password
  #     - POSTGRES_USER=your_user
  #     - POSTGRES_DB=diamond_diaries
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - diamond-diaries-network

networks:
  diamond-diaries-network:
    driver: bridge

# Uncomment if using database service
# volumes:
#   postgres_data: